
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 05 17:45:24 GMT-03:00 2016
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int PONER = 29;
  public static final int SIGNO_MAS = 14;
  public static final int PUNTO = 16;
  public static final int SIGNO_MAYOR_IGUAL = 31;
  public static final int PARENTESIS_IZQUIERDO = 9;
  public static final int CORCHETE_DERECHO = 20;
  public static final int ENTONCES = 13;
  public static final int SIGNO_MULT = 11;
  public static final int IDFUNC = 4;
  public static final int VERDADERO = 18;
  public static final int NADA = 24;
  public static final int CORCHETE_IZQUIERDO = 17;
  public static final int ID = 3;
  public static final int PARENTESIS_DERECHO = 10;
  public static final int NUM = 2;
  public static final int FALSO = 12;
  public static final int SIGNO_MENOR_IGUAL = 22;
  public static final int COMA = 7;
  public static final int EOF = 0;
  public static final int SIGNO_NO = 8;
  public static final int SINO = 26;
  public static final int SIGNO_MENOS = 15;
  public static final int LLAMAR = 32;
  public static final int SI = 27;
  public static final int error = 1;
  public static final int SIGNO_IGUAL = 19;
  public static final int EN = 30;
  public static final int SIGNO_DISTINTO = 28;
  public static final int RECIBE = 6;
  public static final int MIENTRAS = 25;
  public static final int HACER = 23;
  public static final int PONER_EN = 33;
  public static final int SIGNO_Y = 21;
  public static final int FUNCION = 5;
}

