
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 31 20:20:25 GMT-03:00 2016
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int PONER = 25;
  public static final int SIGNO_MAS = 10;
  public static final int PUNTO = 12;
  public static final int SIGNO_MAYOR_IGUAL = 27;
  public static final int PARENTESIS_IZQUIERDO = 5;
  public static final int ENTONCES = 9;
  public static final int SIGNO_MULT = 7;
  public static final int VERDADERO = 14;
  public static final int NADA = 20;
  public static final int ID = 3;
  public static final int PARENTESIS_DERECHO = 6;
  public static final int NUM = 2;
  public static final int FALSO = 8;
  public static final int SIGNO_MENOR_IGUAL = 18;
  public static final int EOF = 0;
  public static final int SIGNO_NO = 4;
  public static final int SINO = 22;
  public static final int PARENTESIS_CURVO_DERECHO = 16;
  public static final int SIGNO_MENOS = 11;
  public static final int SI = 23;
  public static final int error = 1;
  public static final int SIGNO_IGUAL = 15;
  public static final int EN = 26;
  public static final int SIGNO_DISTINTO = 24;
  public static final int MIENTRAS = 21;
  public static final int HACER = 19;
  public static final int PARENTESIS_CURVO_IZQUIERDO = 13;
  public static final int SIGNO_Y = 17;
}

